//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMBODEGA
    {
        public Nullable<int> CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public string BODEGUERO { get; set; }
        public Nullable<decimal> NOING { get; set; }
        public Nullable<decimal> NOEGR { get; set; }
        public Nullable<decimal> NOFACTURA { get; set; }
        public Nullable<decimal> NOPEDIDO { get; set; }
        public Nullable<decimal> NOCOM { get; set; }
        public Nullable<decimal> NODCOM { get; set; }
        public Nullable<decimal> NOAJI { get; set; }
        public Nullable<decimal> NOAJE { get; set; }
        public Nullable<decimal> NOTRAIN { get; set; }
        public Nullable<decimal> NOTRAEG { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> NOOCO { get; set; }
        public Nullable<decimal> NONOTA { get; set; }
        public Nullable<decimal> NCR { get; set; }
        public Nullable<decimal> NCRINT { get; set; }
        public Nullable<decimal> NORETENCION { get; set; }
        public Nullable<decimal> NCRPROV { get; set; }
        public decimal NOCARGAEGRESO { get; set; }
        public decimal NOCARGAINGRESO { get; set; }
        public decimal NUMGUIAREMISION { get; set; }
        public int NOPROCESO { get; set; }
        public string SERIE { get; set; }
        public string NOAUTORIZACIONFAC { get; set; }
        public Nullable<System.DateTime> FECHAVDESDEFAC { get; set; }
        public Nullable<System.DateTime> FECHAVHASTAFAC { get; set; }
        public string NOAUTOSRIFAC { get; set; }
        public string NOAUTORIZACIONNCR { get; set; }
        public Nullable<System.DateTime> FECHAVDESDENCR { get; set; }
        public Nullable<System.DateTime> FECHAVHASTANCR { get; set; }
        public string NOAUTOSRINCR { get; set; }
        public string NOAUTORIZACIONNVT { get; set; }
        public Nullable<System.DateTime> FECHAVDESDENVT { get; set; }
        public Nullable<System.DateTime> FECHAVHASTANVT { get; set; }
        public string NOAUTOSRINVT { get; set; }
        public string NOAUTORIZACIONRET { get; set; }
        public Nullable<System.DateTime> FECHAVDESDERET { get; set; }
        public Nullable<System.DateTime> FECHAVHASTARET { get; set; }
        public string NOAUTOSRIRET { get; set; }
        public string BODATS { get; set; }
        public int NOCONTROLPACIENTE { get; set; }
        public string CODIGO_BODEGA { get; set; }
        public decimal NOIMPORTACION { get; set; }
        public decimal numguiaremisionpos { get; set; }
        public string TELEFONO { get; set; }
    }
}
