//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMCANTON
    {
        public string codigo { get; set; }
        public string provincia { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public string CODIGOSAP { get; set; }
        public string codigo_sap_provincia { get; set; }
    }
}
