//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMCLIENTE
    {
        public string CODIGO { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string NEGOCIO { get; set; }
        public string REPRESENTA { get; set; }
        public string RUC { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONOS { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string TIPO { get; set; }
        public string CATEGORIA { get; set; }
        public string PROVINCIA { get; set; }
        public string CANTON { get; set; }
        public string PARROQUIA { get; set; }
        public string SECTOR { get; set; }
        public string RUTA { get; set; }
        public string CTACLIENTE { get; set; }
        public Nullable<decimal> CUPO { get; set; }
        public string GRUPO { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public string CODFRE { get; set; }
        public string CREDITO { get; set; }
        public Nullable<int> DIA { get; set; }
        public Nullable<System.DateTime> FECDESDE { get; set; }
        public Nullable<System.DateTime> FECHAING { get; set; }
        public Nullable<System.DateTime> FECULTCOM { get; set; }
        public Nullable<System.DateTime> FECELIMINA { get; set; }
        public string ESTADO { get; set; }
        public string TDCREDITO { get; set; }
        public Nullable<int> DIASCREDIT { get; set; }
        public string VENDEDOR { get; set; }
        public string FORMAPAG { get; set; }
        public string CREDITOA { get; set; }
        public string IVA { get; set; }
        public string BACKORDER { get; set; }
        public string RETENPED { get; set; }
        public string CONFINAL { get; set; }
        public string CLASE { get; set; }
        public string OBSERVACION { get; set; }
        public string TIPONEGO { get; set; }
        public string CODTMP { get; set; }
        public string TIPODOC { get; set; }
        public string TIPOCUENTA { get; set; }
        public string CLIENTEWEB { get; set; }
        public string CODCLIENTEDOMI { get; set; }
        public string CLIENTEDOMI { get; set; }
        public string REFERENCIA { get; set; }
        public string TIPOCONTRIBUYENTE { get; set; }
        public string RETIENEFUENTE { get; set; }
        public string RETIENEIVA { get; set; }
        public string ZONA { get; set; }
        public Nullable<System.DateTime> FECNAC { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string OPEMOD { get; set; }
        public double PORDESSUGERIDO { get; set; }
        public string EMAILSECUNDARIO { get; set; }
        public string fechaenvioweb { get; set; }
        public int FACTURAELECTRONICA { get; set; }
        public string CLAVEFE { get; set; }
        public string SUBIRWEB { get; set; }
        public string TIPOPERSONA { get; set; }
        public string SEXO { get; set; }
        public string ESTADOCIVIL { get; set; }
        public string ORIGENINGRESO { get; set; }
        public string TIPOPAGO { get; set; }
        public Nullable<System.DateTime> FECHADESDE { get; set; }
        public Nullable<System.DateTime> FECHAHASTA { get; set; }
        public string BENEFICIARIO { get; set; }
        public string NOCONTRATO { get; set; }
        public string TIPOPERSONAADICIONAL { get; set; }
        public string GERENTE { get; set; }
        public string TELEFONO { get; set; }
        public string CONTACTOPAGO { get; set; }
        public string CORREO1 { get; set; }
        public string CORREO2 { get; set; }
        public string CARGO1 { get; set; }
        public string CARGO2 { get; set; }
        public string OBSERVACIONADICIONAL { get; set; }
        public string PAGOCUOTAS { get; set; }
        public Nullable<int> NUMCUOTAS { get; set; }
        public Nullable<int> CUOTA1 { get; set; }
        public Nullable<int> CUOTA2 { get; set; }
        public Nullable<int> CUOTA3 { get; set; }
        public Nullable<int> CUOTA4 { get; set; }
        public Nullable<int> CUOTA5 { get; set; }
        public string EJEX { get; set; }
        public string EJEY { get; set; }
        public string CLIENTEMOVIL { get; set; }
        public string ESTADOPARAWEB { get; set; }
        public string CLIRELACIONADO { get; set; }
        public string VENDEDORAUX { get; set; }
        public string CANAL { get; set; }
        public string SUBCANAL { get; set; }
        public string grupocliente { get; set; }
        public string grupocredito { get; set; }
        public string EWEB { get; set; }
        public string nombre { get; set; }
        public string FACTURABLE { get; set; }
        public string DEUDAS { get; set; }
        public Nullable<decimal> ANTICIPO { get; set; }
        public string CIUDAD { get; set; }
        public string coordenada { get; set; }
        public string barrio { get; set; }
        public string tipodocumento { get; set; }
        public string CODIGOSAP { get; set; }
        public string CodShip { get; set; }
        public string longuitud { get; set; }
        public string latitud { get; set; }
        public string TipoLocalidad { get; set; }
        public string numero { get; set; }
        public string CORREOCARRO { get; set; }
        public string CLAVECARRO { get; set; }
    }
}
