//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMCABPEDIDO
    {
        public decimal SECAUTO { get; set; }
        public string TIPO { get; set; }
        public int BODEGA { get; set; }
        public decimal NUMERO { get; set; }
        public decimal SECUENCIAL { get; set; }
        public string CLIENTE { get; set; }
        public string VENDEDOR { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> NETO { get; set; }
        public Nullable<double> PESO { get; set; }
        public Nullable<double> VOLUMEN { get; set; }
        public string OPERADOR { get; set; }
        public string COMENTARIO { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<decimal> FACTURA { get; set; }
        public Nullable<decimal> GUIA { get; set; }
        public string DOCFAC { get; set; }
        public string DIASCRED { get; set; }
        public string GRAVAIVA { get; set; }
        public string CREDITO { get; set; }
        public Nullable<byte> NUMCUOTAS { get; set; }
        public Nullable<System.DateTime> FECHALIBERACION { get; set; }
        public string HORALIBERACION { get; set; }
        public string OPERLIBERACION { get; set; }
        public Nullable<double> TRANSPORTE { get; set; }
        public Nullable<double> RECARGO { get; set; }
        public string TIPOCLIENTE { get; set; }
        public string SUCURSAL { get; set; }
        public string ESMOVIL { get; set; }
        public string SECAUTOPEDMOVIL { get; set; }
        public string SERIEPOLOCLUB { get; set; }
        public string CODIGORETAILPRO { get; set; }
        public decimal numeroplantilla { get; set; }
        public Nullable<decimal> CODIGOPEDIDO { get; set; }
    }
}
