//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMCANTON
    {
        public string codigo { get; set; }
        public string provincia { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public string CODIGOSAP { get; set; }
        public string codigo_sap_provincia { get; set; }
    }
}
