//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMDETPEDIDO
    {
        public int LINEA { get; set; }
        public decimal SECUENCIAL { get; set; }
        public string ITEM { get; set; }
        public Nullable<int> CANTIC { get; set; }
        public Nullable<int> CANTIU { get; set; }
        public Nullable<int> CANTFUN { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
        public Nullable<double> PORDES { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> ICE { get; set; }
        public Nullable<double> NETO { get; set; }
        public Nullable<double> COSTOP { get; set; }
        public Nullable<double> COSTOU { get; set; }
        public string TIPOITEM { get; set; }
        public string FORMAVTA { get; set; }
        public string ESTADO { get; set; }
        public string FACTURADO { get; set; }
        public string GRAVAIVA { get; set; }
        public Nullable<int> LINGENCONDICION { get; set; }
        public Nullable<double> PORDES2 { get; set; }
        public string TIPOPEDIDO { get; set; }
        public string DETALLE { get; set; }
        public Nullable<System.DateTime> fechaela { get; set; }
        public Nullable<System.DateTime> fechaven { get; set; }
        public string lote { get; set; }
        public string codigo_doc { get; set; }
        public string tipoproducto { get; set; }
        public string lista { get; set; }
    }
}
