//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMITEM
    {
        public string ITEM { get; set; }
        public string NOMBRE { get; set; }
        public string NOMBRECORTO { get; set; }
        public string CATEGORIA { get; set; }
        public string FAMILIA { get; set; }
        public string LINEA { get; set; }
        public string MARCA { get; set; }
        public string PRESENTA { get; set; }
        public string ESTADO { get; set; }
        public string DISPOVEN { get; set; }
        public string IVA { get; set; }
        public string BIEN { get; set; }
        public string PROVEEDOR { get; set; }
        public Nullable<decimal> FACTOR { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public Nullable<decimal> STOCKMI { get; set; }
        public Nullable<decimal> STOCKMA { get; set; }
        public Nullable<double> PESO { get; set; }
        public Nullable<double> VOLUMEN { get; set; }
        public Nullable<double> PRECIO0 { get; set; }
        public Nullable<double> PRECIO1 { get; set; }
        public Nullable<double> PRECIO2 { get; set; }
        public Nullable<double> PRECIO3 { get; set; }
        public Nullable<double> PRECIO4 { get; set; }
        public Nullable<double> PRECIO5 { get; set; }
        public Nullable<double> PVP { get; set; }
        public string ITEMR { get; set; }
        public Nullable<System.DateTime> ULTVEN { get; set; }
        public Nullable<System.DateTime> ULTCOM { get; set; }
        public Nullable<double> COSTOP { get; set; }
        public Nullable<double> COSTOU { get; set; }
        public string OBSERVA { get; set; }
        public string GRUPO { get; set; }
        public string COMBO { get; set; }
        public string REGALO { get; set; }
        public string CODPROV { get; set; }
        public Nullable<double> PORUTI { get; set; }
        public Nullable<double> PORUTIVENTA { get; set; }
        public string CODBARRA { get; set; }
        public string CANFRA { get; set; }
        public int STOCKMAY { get; set; }
        public double PORUTIPRE0 { get; set; }
        public double PORUTIPRE1 { get; set; }
        public double PORUTIPRE2 { get; set; }
        public double PORUTIPRE3 { get; set; }
        public double PORUTIPRE4 { get; set; }
        public double PORUTIPRE5 { get; set; }
        public double LITROS { get; set; }
        public string WEB { get; set; }
        public string OFERTA { get; set; }
        public double POFERTA { get; set; }
        public string NOVEDAD { get; set; }
        public string IMAGEN { get; set; }
        public decimal CANTCOMPRA { get; set; }
        public string SOLOPOS { get; set; }
        public string CUENTAVENTA { get; set; }
        public string ESPT { get; set; }
        public string IMAGENADICIONAL { get; set; }
        public string TIENECTAVENTA { get; set; }
        public string tipoprofal { get; set; }
        public double PORDESSUGERIDO { get; set; }
        public Nullable<int> NUMCOTIZACION { get; set; }
        public string SOLORECETA { get; set; }
        public string PSICOTROPICO { get; set; }
        public string TRATAMIENTOCONTINUO { get; set; }
        public string CONTROLLOTE { get; set; }
        public string seccion { get; set; }
        public string percha { get; set; }
        public string REGSANITARIO { get; set; }
        public string EWEB { get; set; }
        public string TIPOPRODUCTO { get; set; }
        public Nullable<decimal> cantidadxcaja { get; set; }
        public string CodShip { get; set; }
        public string descripcion { get; set; }
        public string subcategoria { get; set; }
        public string CARRO { get; set; }
        public string ESTAENCARRO { get; set; }
    }
}
