//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMITEMBOD
    {
        public int BODEGA { get; set; }
        public string ITEM { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public Nullable<System.DateTime> ULTFECING { get; set; }
        public Nullable<System.DateTime> ULTFECEGR { get; set; }
    }
}
