//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMMARCA
    {
        public string CODIGO { get; set; }
        public string CATEGORIA { get; set; }
        public string FAMILIA { get; set; }
        public string LINEA { get; set; }
        public string NOMBRE { get; set; }
        public string ESTADO { get; set; }
        public string EWEB { get; set; }
        public string CODIGOSAP { get; set; }
    }
}
