//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMPARAMETROV
    {
        public string NOMBRECIA { get; set; }
        public string MODULO { get; set; }
        public Nullable<decimal> ANIO { get; set; }
        public string TIPOCOSTO { get; set; }
        public Nullable<int> FACLIN { get; set; }
        public Nullable<decimal> SECUENCIAL { get; set; }
        public Nullable<decimal> NUMGUIA { get; set; }
        public Nullable<double> IVA { get; set; }
        public string CATEGORIA { get; set; }
        public string FAMILIA { get; set; }
        public string LINEA { get; set; }
        public string MARCA { get; set; }
        public string MONEDA { get; set; }
        public string INTEGCXC { get; set; }
        public Nullable<int> BODFAC { get; set; }
        public Nullable<decimal> NUMCONDI { get; set; }
        public string INTVENCON { get; set; }
        public string CLIENTE { get; set; }
        public string TIPOMETA { get; set; }
        public string SERIE { get; set; }
        public string NOAUTO { get; set; }
        public Nullable<System.DateTime> FECHAVAL { get; set; }
        public string IMPPOS { get; set; }
        public Nullable<int> RANGOIMP { get; set; }
        public string ACTPOS { get; set; }
        public string CANGUI { get; set; }
        public string FACSTK { get; set; }
        public string IMPSRI { get; set; }
        public string POSIMP { get; set; }
        public Nullable<decimal> PORCOM { get; set; }
        public string CARVEN { get; set; }
        public string VARVEN { get; set; }
        public string IMPCABGUI { get; set; }
        public Nullable<decimal> NUMGRUPO { get; set; }
        public Nullable<int> BODAUTO { get; set; }
        public Nullable<decimal> NUMCARGA { get; set; }
        public string CPAG { get; set; }
        public string ACTCOND { get; set; }
        public Nullable<decimal> NUMCOTI { get; set; }
        public string GENDFA { get; set; }
        public string CONFAC { get; set; }
        public string BUSCA1 { get; set; }
        public string BUSCA2 { get; set; }
        public string MPORUTI { get; set; }
        public string AUTOCODIGO { get; set; }
        public string DESACT { get; set; }
        public string NOAUTORET { get; set; }
        public string SERIERET { get; set; }
        public Nullable<System.DateTime> FECHAVALRET { get; set; }
        public string CAMPRECIO { get; set; }
        public string NOAUTONVT { get; set; }
        public string SERIENVT { get; set; }
        public Nullable<System.DateTime> FECHAVALNVT { get; set; }
        public string NOAUTONCR { get; set; }
        public string SERIENCR { get; set; }
        public Nullable<System.DateTime> FECHAVALNCR { get; set; }
        public string IVANVT { get; set; }
        public string intconcaja { get; set; }
        public string intnofac { get; set; }
        public Nullable<decimal> NUMGUIATRANS { get; set; }
        public int NVTLIN { get; set; }
        public string CONTROLCUPO { get; set; }
        public int PRECIODEFAULT { get; set; }
        public int BODEGAPOS { get; set; }
        public string AUTOCODITEM { get; set; }
        public string AUTOCALPRECIO { get; set; }
        public string POSVENTACREDITO { get; set; }
        public int POSINICIOCABECERA { get; set; }
        public int POSINICIOPIE { get; set; }
        public int POSINICIODETALLE { get; set; }
        public int POSFACLIN { get; set; }
        public int POSTIPODETALLE { get; set; }
        public int POSINICIOINFOPOS { get; set; }
        public int POSLINEAFINAL { get; set; }
        public int POSVECESCOPIA { get; set; }
        public string CONTROLVALVENCREDITO { get; set; }
        public string CONTROLVALVENCONTADO { get; set; }
        public decimal NUMEROAUTOVENTA { get; set; }
        public decimal NLOCALIDAD { get; set; }
        public int POSESQUEMAPRECIOS { get; set; }
        public string FACTURAHASTA { get; set; }
        public decimal OTRAEMPRWEB { get; set; }
        public string RUTADOMI { get; set; }
        public string POSIMPDATOSEMPRESA { get; set; }
        public string POSDATOLINEA0 { get; set; }
        public string POSDATOPROPIETARIO { get; set; }
        public string POSINICIOPIEDINAMICO { get; set; }
        public string OCULTARCOLUMNACAJAS { get; set; }
        public string DESCUENTOSENCADENA { get; set; }
        public string RECARGAIVANVT { get; set; }
        public string GRUPTOVENTA { get; set; }
        public int ESQUEMAPAGOCOMI { get; set; }
        public int LONGITUDAUTOCODITEM { get; set; }
        public string CONNFVD { get; set; }
        public string CENTROCOSTO { get; set; }
        public int POSPRECIOVENTA { get; set; }
        public string mensajefac { get; set; }
        public string LISTAPRECIO { get; set; }
        public string LINEAREDONDEA { get; set; }
        public string FACTURAXBODEGA { get; set; }
        public Nullable<int> ttesqcomi { get; set; }
        public string cnfvd { get; set; }
        public string coculcolumca { get; set; }
        public string chabdescad { get; set; }
        public string crecivanv { get; set; }
        public Nullable<int> clongcodi { get; set; }
        public string cautocalprecio { get; set; }
        public string cautocoditem { get; set; }
        public Nullable<int> NUMPROVINCIAS { get; set; }
        public string serieguia { get; set; }
        public string IMPRIMESERIE { get; set; }
        public string proteina { get; set; }
        public string EPRECIO { get; set; }
        public string UNASOLABODEGA { get; set; }
        public string FACTURAELECTRONICA { get; set; }
        public string NOMBRESERVIDOR { get; set; }
        public string NOMBREBASE { get; set; }
        public decimal VALORMAXCF { get; set; }
        public int BODEGAFE { get; set; }
        public string usarcodbar { get; set; }
        public string conexionvb { get; set; }
        public string controlprod { get; set; }
        public string numeroorden { get; set; }
        public string FACENTPARCIAL { get; set; }
        public string MOSADVCAR { get; set; }
        public string secuencialuniconcr { get; set; }
        public string conservarpedido { get; set; }
        public string IMPHOJAC { get; set; }
        public string tienedetfac { get; set; }
        public string NUMFACDELPEDIDO { get; set; }
        public string usardecimales { get; set; }
        public string posrangoprecio { get; set; }
        public decimal numerotoma { get; set; }
        public string tienedessol { get; set; }
        public string facturanegativo { get; set; }
        public string ESQUEMAFARMA { get; set; }
        public string impresoracargapos { get; set; }
        public string imprimemenahorro { get; set; }
        public string imprimecodigopos { get; set; }
        public string UNILEVER { get; set; }
        public string CODDISTRIBUIDOR { get; set; }
        public string tipodocventa { get; set; }
        public string itemcredihogar { get; set; }
        public double porintcreditomensual { get; set; }
        public string nedetel { get; set; }
        public string facnedetel { get; set; }
        public string ESNOTAVENTA { get; set; }
        public string odbcempresa { get; set; }
        public string controlcomisariato { get; set; }
        public string CAMPRECIOPOS { get; set; }
        public string campremantenimiento { get; set; }
        public string FACSERSOS { get; set; }
        public decimal numeroplantilla { get; set; }
        public string DATOSCLIPOS { get; set; }
        public string INGPREAJI { get; set; }
        public string cambiavenpos { get; set; }
        public string POSGENERAANTNCR { get; set; }
        public string ESRANCHO { get; set; }
        public string posmostrarmarca { get; set; }
        public string POSCONSERVICIO { get; set; }
        public string posconalumno { get; set; }
        public string POSDOSLINEAS { get; set; }
        public string poscontrolpreciocosto { get; set; }
        public string posvendedor { get; set; }
        public string cartera { get; set; }
        public string USACARROCOMPRA { get; set; }
    }
}
