//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMPARAMETROC
    {
        public string MODULO { get; set; }
        public string NOMBRECIA { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<decimal> SECUENCIAL { get; set; }
        public Nullable<decimal> NUMHOJA { get; set; }
        public string PROVINCIA { get; set; }
        public string CANTON { get; set; }
        public string PARROQUIA { get; set; }
        public string SECTOR { get; set; }
        public string INTEGCXC { get; set; }
        public string LETRAINI { get; set; }
        public Nullable<decimal> NUMCLIENTE { get; set; }
        public string AUTOCLI { get; set; }
        public string INTCXCCON { get; set; }
        public Nullable<System.DateTime> FECHACXC { get; set; }
        public Nullable<decimal> GUIACOB { get; set; }
        public Nullable<decimal> NOCOBRO { get; set; }
        public Nullable<decimal> VALORNCR { get; set; }
        public string CAJAC { get; set; }
        public string AUTOCODIGO { get; set; }
        public string FECHACAJA { get; set; }
        public string CAMCRE { get; set; }
        public string CREDDEF { get; set; }
        public string CUPOCARTERA { get; set; }
        public string CONTROLDEPOCIERRE { get; set; }
        public string COBRADOR { get; set; }
        public string CONTROLRECIBO { get; set; }
        public string GENERACUOTAS { get; set; }
        public string IMPNCR2 { get; set; }
        public string REPETIRNRECIBO { get; set; }
        public string CONTROLBASESRET { get; set; }
        public string BENEDEFAULT { get; set; }
        public string VENDEDORPOS { get; set; }
        public string CODVENPOS { get; set; }
        public string SUCURSALAUTO { get; set; }
        public string TIPOCLIENTE { get; set; }
        public int NUMPACIENTE { get; set; }
        public int NUMCONTRATO { get; set; }
        public int NUMENVIOLAB { get; set; }
        public int NUMDOCTOR { get; set; }
        public int diasgraciavencuota { get; set; }
        public string interes { get; set; }
        public string generandb { get; set; }
        public string generapagondb { get; set; }
        public double porintmoradia { get; set; }
        public string controlcupofvd { get; set; }
        public string posbloqueofaccre { get; set; }
        public string CLIENTEMODELOCARRO { get; set; }
    }
}
